# Generated by Django 3.2.20 on 2023-07-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(blank=True, max_length=20)),
                ('Lastname', models.CharField(blank=True, max_length=20)),
                ('Username', models.CharField(blank=True, max_length=20)),
                ('Gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Phonenumber', models.CharField(blank=True, max_length=15)),
                ('Address', models.TextField(blank=True, max_length=255)),
            ],
        ),
    ]
