# Generated by Django 3.2.20 on 2023-07-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20230716_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='Recently',
        ),
    ]
