# Generated by Django 3.2.20 on 2023-07-17 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20230717_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='History',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Saved',
        ),
    ]
