# Generated by Django 3.2.20 on 2023-09-14 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0008_userdetail_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='checkoutprice',
            new_name='checkout_price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Username',
        ),
        migrations.AddField(
            model_name='orders',
            name='relation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='relation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Address',
            field=models.TextField(blank=True, default='www'),
        ),
    ]
