# Generated by Django 3.2.20 on 2023-09-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20230914_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone_number',
            field=models.CharField(default='07063475466', max_length=11),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Address',
            field=models.TextField(blank=True),
        ),
    ]
