# Generated by Django 3.2.20 on 2023-09-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20230914_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('S', 'Successfully delivered'), ('P', ' Delivery in progress'), ('F', 'Failed to process checkout')], default='S', max_length=35),
        ),
    ]
