# Generated by Django 3.2.20 on 2023-09-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20230914_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='username',
            field=models.CharField(default='uwuwuwu', max_length=30),
        ),
    ]
