# Generated by Django 3.2.20 on 2023-07-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CakeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(default='/static/Cake/', max_length=50)),
                ('price', models.IntegerField()),
                ('price_to_sell', models.IntegerField()),
                ('product_code', models.CharField(default='cake-', max_length=20, unique=True)),
                ('description', models.TextField(max_length=100)),
                ('notice', models.TextField(max_length=100)),
                ('validity', models.CharField(choices=[('Y', 'Available'), ('N', 'Not Available')], max_length=15)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
