# Generated by Django 3.2.20 on 2023-07-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berylapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakemodel',
            name='product_class',
            field=models.CharField(default='Cake', max_length=20),
        ),
        migrations.AlterField(
            model_name='cakemodel',
            name='picture',
            field=models.CharField(max_length=50),
        ),
    ]
