# Generated by Django 3.2.20 on 2023-07-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berylapp', '0002_auto_20230702_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='userDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=6)),
                ('Email', models.EmailField(max_length=254)),
                ('Phonenumber', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='cakemodel',
            name='picture',
            field=models.CharField(default='/static/Cake/', max_length=50),
        ),
    ]
