# Generated by Django 3.2.20 on 2023-07-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berylapp', '0004_userdetail_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='Address',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Firstname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Lastname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Phonenumber',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Username',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
