# Generated by Django 3.2.20 on 2023-07-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berylapp', '0005_auto_20230703_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(default='/static/Appliance/', max_length=50)),
                ('price', models.IntegerField()),
                ('price_to_sell', models.IntegerField()),
                ('product_code', models.CharField(default='appliance-', max_length=20, unique=True)),
                ('product_class', models.CharField(default='Appliance', max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('notice', models.TextField(max_length=100)),
                ('validity', models.CharField(choices=[('Y', 'Available'), ('N', 'Not Available')], max_length=15)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(default='/static/Book/', max_length=50)),
                ('price', models.IntegerField()),
                ('price_to_sell', models.IntegerField()),
                ('product_code', models.CharField(default='book-', max_length=20, unique=True)),
                ('product_class', models.CharField(default='Book', max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('notice', models.TextField(max_length=100)),
                ('validity', models.CharField(choices=[('Y', 'Available'), ('N', 'Not Available')], max_length=15)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FashionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(default='/static/Fashion/', max_length=50)),
                ('price', models.IntegerField()),
                ('price_to_sell', models.IntegerField()),
                ('product_code', models.CharField(default='fashion-', max_length=20, unique=True)),
                ('product_class', models.CharField(default='Fashion', max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('notice', models.TextField(max_length=100)),
                ('validity', models.CharField(choices=[('Y', 'Available'), ('N', 'Not Available')], max_length=15)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MugModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(default='/static/Mug/', max_length=50)),
                ('price', models.IntegerField()),
                ('price_to_sell', models.IntegerField()),
                ('product_code', models.CharField(default='mug-', max_length=20, unique=True)),
                ('product_class', models.CharField(default='Mug', max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('notice', models.TextField(max_length=100)),
                ('validity', models.CharField(choices=[('Y', 'Available'), ('N', 'Not Available')], max_length=15)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneDeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(default='/static/PhoneDevice/', max_length=50)),
                ('price', models.IntegerField()),
                ('price_to_sell', models.IntegerField()),
                ('product_code', models.CharField(default='phonedevice-', max_length=20, unique=True)),
                ('product_class', models.CharField(default='PhoneDevice', max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('notice', models.TextField(max_length=100)),
                ('validity', models.CharField(choices=[('Y', 'Available'), ('N', 'Not Available')], max_length=15)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupermarketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(default='/static/Supermarket/', max_length=50)),
                ('price', models.IntegerField()),
                ('price_to_sell', models.IntegerField()),
                ('product_code', models.CharField(default='supermarket-', max_length=20, unique=True)),
                ('product_class', models.CharField(default='Supermarket', max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('notice', models.TextField(max_length=100)),
                ('validity', models.CharField(choices=[('Y', 'Available'), ('N', 'Not Available')], max_length=15)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UtensilModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(default='/static/Utensil/', max_length=50)),
                ('price', models.IntegerField()),
                ('price_to_sell', models.IntegerField()),
                ('product_code', models.CharField(default='utensil-', max_length=20, unique=True)),
                ('product_class', models.CharField(default='Utensil', max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('notice', models.TextField(max_length=100)),
                ('validity', models.CharField(choices=[('Y', 'Available'), ('N', 'Not Available')], max_length=15)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(default='/static/Wine/', max_length=50)),
                ('price', models.IntegerField()),
                ('price_to_sell', models.IntegerField()),
                ('product_code', models.CharField(default='wine-', max_length=20, unique=True)),
                ('product_class', models.CharField(default='Wine', max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('notice', models.TextField(max_length=100)),
                ('validity', models.CharField(choices=[('Y', 'Available'), ('N', 'Not Available')], max_length=15)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Address',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
