# Generated by Django 3.2.20 on 2023-07-16 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berylapp', '0006_auto_20230716_1511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userDetail',
        ),
    ]
