# Generated by Django 3.2.20 on 2023-07-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berylapp', '0007_delete_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliancemodel',
            name='picture',
            field=models.ImageField(upload_to='Appliance/'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='picture',
            field=models.ImageField(upload_to='Book/'),
        ),
        migrations.AlterField(
            model_name='cakemodel',
            name='picture',
            field=models.ImageField(upload_to='Cake/'),
        ),
        migrations.AlterField(
            model_name='fashionmodel',
            name='picture',
            field=models.ImageField(upload_to='Fashion/'),
        ),
        migrations.AlterField(
            model_name='mugmodel',
            name='picture',
            field=models.ImageField(upload_to='MugCup/'),
        ),
        migrations.AlterField(
            model_name='phonedevicemodel',
            name='picture',
            field=models.ImageField(upload_to='PhoneDevice/'),
        ),
        migrations.AlterField(
            model_name='supermarketmodel',
            name='picture',
            field=models.ImageField(upload_to='Supermarket/'),
        ),
        migrations.AlterField(
            model_name='utensilmodel',
            name='picture',
            field=models.ImageField(upload_to='Utensil/'),
        ),
        migrations.AlterField(
            model_name='winemodel',
            name='picture',
            field=models.ImageField(upload_to='Wine/'),
        ),
    ]
