# Generated by Django 3.2.20 on 2023-07-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berylapp', '0008_auto_20230716_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliancemodel',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appliancemodel',
            name='notice',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='notice',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cakemodel',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cakemodel',
            name='notice',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fashionmodel',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fashionmodel',
            name='notice',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mugmodel',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mugmodel',
            name='notice',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phonedevicemodel',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phonedevicemodel',
            name='notice',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='utensilmodel',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='utensilmodel',
            name='notice',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='winemodel',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='winemodel',
            name='notice',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
